name: 'Publish BBSSG site to GitHub pages'
description: 'Publishes a BBSSG site to a gh-pages branch of your repo.'
author: 'Andrew Bridge'
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
