# This workflow will generate and publish a site using BBSSG
name: Publish BBSSG demo site

on:
  push:
    branches: [main]

jobs:
  generate-and-deploy:
    name: Generate and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - run: |
        npm run build
        git checkout --orphan gh-pages
        git reset
        git clean -fd
        mv ./dist/* .
        rm -d ./dist
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
